### ISSUE TITLE
Foreign Lobbying Card

### ISSUE THREAD

**Issue by crdunwel** [sunlightlabs/openfederal#12]
- [ ] Country (India, etc)
- [ ] Client (Embassy of India, etc)
- [ ] Foreign Agent (Lobbyist, etc)

**Comment by crdunwel** [comment]
This is a preliminary attribute list. There are example entries for each. Consult @boblannon if you have questions.

**Country** http://foreign.influenceexplorer.com/location-profile/285/Azerbaijan

- [ ] Name
- [ ] Map image
- [ ] Truncated Client list (name, link, date range)
- [ ] Top Issue list (name, amount)

**Client** ex. http://foreign.influenceexplorer.com/client-profile/129758

- [ ] Name
- [ ] Client Summary
- [ ] Location
- [ ] Truncated Foreign Agent list (name, date range)
- [ ] Payments

**Foreign Agent (Registrant)** ex. http://foreign.influenceexplorer.com/reg-profile/5884

- [ ] Name
- [ ] Truncated Client list (name, date range)
- [ ] Payments

**Comment by cweber** [comment]
@boblannon, take a look at the way I characterized issues on the location cards. Does that make sense? I couldn't find any example locations that had what I would consider issues, so I don't really know what the data is like.

![foreign lobbying - client small](https://cloud.githubusercontent.com/assets/417657/10443476/b3e844ac-7129-11e5-9545-27f22c1e7d11.png)
![foreign lobbying - client](https://cloud.githubusercontent.com/assets/417657/10443474/b3e73422-7129-11e5-9f7d-c12df6c0e01c.png)
![foreign lobbying - country small](https://cloud.githubusercontent.com/assets/417657/10443473/b3e57222-7129-11e5-93ae-c38a2fdb964b.png)
![foreign lobbying - country](https://cloud.githubusercontent.com/assets/417657/10443513/1a6cc748-712a-11e5-8701-b89629b217f0.png)
![foreign lobbying - registrant small](https://cloud.githubusercontent.com/assets/417657/10443475/b3e79b9c-7129-11e5-98dd-9838bb695314.png)
![foreign lobbying - registrant](https://cloud.githubusercontent.com/assets/417657/10443477/b3e8f51e-7129-11e5-8669-e558f66f4b71.png)

**Comment by boblannon** [comment]
You're right: only domestic lobbying has issues. Foreign lobbying doesn't have them.

**Comment by cweber** [comment]
Gotcha. Now edited and moving on to the next property!

![foreign lobbying - country small](https://cloud.githubusercontent.com/assets/417657/10460227/6d6c68d2-71a1-11e5-9638-6a9292d308aa.png)
![foreign lobbying - country](https://cloud.githubusercontent.com/assets/417657/10460226/6d6b9baa-71a1-11e5-9fd2-a653dd6018b6.png)
