### ISSUE TITLE
Capitol Words Card

### ISSUE THREAD

**Issue by crdunwel** [sunlightlabs/openfederal#13]
- [ ] Term Search
- [ ] Person Search

**Comment by crdunwel** [comment]
**Person**

- [ ] Top Words
- [ ] Most Recent

**Term**

- [ ] Stats on who said the term

This one was a lot more open ended because there is so many ways we can represent this data. We also considered not having a card for this API and just having a panel on the side with some of these statistics and link to Capitol Words.

**Comment by cweber** [comment]
![capitol words - term](https://cloud.githubusercontent.com/assets/417657/10772972/27b320cc-7ccf-11e5-9a6f-beeeee6a846a.png)
![capitol words - term small](https://cloud.githubusercontent.com/assets/417657/10772971/27b2e2ba-7ccf-11e5-996a-934bcb12ed3b.png)
![capitol words - person](https://cloud.githubusercontent.com/assets/417657/10772974/27b60e68-7ccf-11e5-8264-6226c06bf577.png)
![capitol words - person small](https://cloud.githubusercontent.com/assets/417657/10772973/27b44948-7ccf-11e5-9005-95c8e674b84a.png)
