### ISSUE TITLE
Congress API Cards

### ISSUE THREAD

**Issue by crdunwel** [sunlightlabs/openfederal#14]
- [ ] Legislators
- [ ] Bills
- [ ] Nominations
- [ ] Regulations
- [ ] Committees

**Comment by cweber** [comment]
@crdunwel On this one, am I reading it correctly that the list you have at the top is a list of all of the different cards that should exist based on Congress API data?

Here is what I see
- [ ] **Legislators** (Name, party, years in congress, state, district, email address, possible map, possible junior/senior ranking)
- [ ] **Bills** (Bill name, bill ID, sponsor, co-sponsor, status) [**I can't read the word under Bill Name** Are date introduced or date passed important?]
- [ ] **Nominations** (Person, Position [name, org], Date, Status [voted, confirmed, rejected] )
- [ ] **Regulations** (Notices [**What is that?**], Title, agency, explanatory text [**is this long? can it be truncated?**], date, pre releas vs relo  [**<-- what?**])
- [ ] **Committees** (Committee Name, chair, ranking member, upcoming hearings, house/senate/joint) [**Does majority vs minority mean which party introduced it?**]

**Comment by crdunwel** [comment]
**Legislators** - ☑
**Bills** - Congress number is the word you can't read. Date introduced/passed is probably important. Other actions we can pass off to congress.gov
**Nominations** - ☑
**Regulations** - Notices are a type of regulation release.There are [proposed rule, final rule, notice.]. See an example from Scout [here](https://scout.sunlightfoundation.com/item/regulation/2015-23551/international-trade-commission-investigations-determinations-modifications-and-rulings-etc-certain-beverage-brewing-capsules-components-thereof-and-products-containing-the-same). The explanatory text can be truncated as much as possible and would ideally do the Scout functionality where it will highlight the searched word (try searching regulations). Not sure difference between pre-release and release but assume it's just a tagged attribute.
**Committees** - For the most part, yes. Each committee actually has a minority/majority component for Rep/Dem. The "official" one is the majority. For instance, see [here](https://oversight.house.gov/) and [here](http://democrats.oversight.house.gov/)

**Comment by cweber** [comment]
Cool. Thanks for the answers. The committee double website situation is super weird.

**Comment by cweber** [comment]
Legislator Cards

![congress api - legislators](https://cloud.githubusercontent.com/assets/417657/10023609/02243e0a-6121-11e5-845d-78b8814229b8.png)
![congress api - legislators small](https://cloud.githubusercontent.com/assets/417657/10023614/06b1a37c-6121-11e5-89ea-0738d8154509.png)

**Comment by cweber** [comment]
Bill Cards

![congress api - bills](https://cloud.githubusercontent.com/assets/417657/10023641/1b7a9f5c-6121-11e5-8b4b-78008ad375ba.png)
![congress api - bills small](https://cloud.githubusercontent.com/assets/417657/10023647/1ea7c6dc-6121-11e5-8712-073a1562f4b1.png)

**Comment by cweber** [comment]
Nomination Cards

![congress api - nominations](https://cloud.githubusercontent.com/assets/417657/10023664/2b52445c-6121-11e5-9258-2ddc2da7b6b9.png)
![congress api - nominations small](https://cloud.githubusercontent.com/assets/417657/10023668/2ebffe9a-6121-11e5-8202-e21f3828ac5d.png)

**Comment by cweber** [comment]
Regulation Cards

![congress api - regulations](https://cloud.githubusercontent.com/assets/417657/10023691/469c2d4a-6121-11e5-9d09-dd807d360e73.png)
![congress api - regulations small](https://cloud.githubusercontent.com/assets/417657/10023698/4c677630-6121-11e5-93ad-0c70b8776d15.png)

**Comment by cweber** [comment]
Committee Cards

![congress api - committees](https://cloud.githubusercontent.com/assets/417657/10023719/66151646-6121-11e5-8dc5-6e48f3aafa42.png)
![congress api - regulations small](https://cloud.githubusercontent.com/assets/417657/10023725/69fcb8b8-6121-11e5-8458-5f1c39a0e485.png)
