### ISSUE TITLE
House/Senate Expenditure Disclosure Cards

### ISSUE THREAD

**Issue by crdunwel** [sunlightlabs/openfederal#15]
- [ ] Expenditure

**Comment by crdunwel** [comment]
So these are the field available to us from the expenditure spreadsheet. Some of these we may not want to use. Check out a "Detail" on https://sunlightfoundation.com/tools/expenditures/ to see an example of the entries. The drawings above includes many of these fields. Seems to make sense to include most of them if they can't be compacted.

- [ ] Bioguide_id
- [ ] Office
- [ ] Quarter
- [ ] Category
- [ ] Date
- [ ] Payee
- [ ] Start Date
- [ ] End Date
- [ ] Purpose
- [ ] Amount
- [ ] Year
- [ ] Transcode
- [ ] Transcodelong
- [ ] Recordid
- [ ] Recip (orig.)

**Comment by cweber** [comment]
I ended up using a pretty small subset of all of those categories. Nice to have options, but a lot of those are duplicative when you want to look at something in summary. Two names that are highly likely to be the same, five things that are some form of date, etc...

![expenditures small](https://cloud.githubusercontent.com/assets/417657/10775880/bf5764ca-7ce2-11e5-8864-be2f6106e9f6.png)
![expenditures](https://cloud.githubusercontent.com/assets/417657/10775879/bf53e12e-7ce2-11e5-85b2-131770ee8eee.png)
