### ISSUE TITLE
"Learn More" button did not work for me

### ISSUE THREAD

**Issue by rshorey** [sunlightlabs/openfederal#20]
ubuntu/firefox

clicking causes the button to change colors but does not redirect as expected. Works fine on my machine on Chrome

BUT more importantly this looks so great and is so responsive!

**Comment by jalbertbowden** [comment]
os x/ff -> can replicate.
altered markup locally and fixed it. now just to figure out how to push...

**Comment by jalbertbowden** [comment]
removed element/its live
