### ISSUE TITLE
Wireframe for search page

### ISSUE THREAD

**Issue by crdunwel** [sunlightlabs/openfederal#9]

**Comment by cweber** [comment]
Was there a conversation about putting the branding bar on OpenFederal? @JennTopper and @crdunwel? My forthcoming wireframes assume that it will be there, but I can drop it if there was a reason for leaving it off of the landing page.

**Comment by cweber** [comment]
Do I need to include about/FAQ/Methodology on this page? It seems like maybe not, since it's just an aggregation tool. I'm going to leave meta nav like that off for now.

**Comment by cweber** [comment]
Here are the wireframes for the homepage (with search) and a search results page in small, medium and large.

![landing page](https://cloud.githubusercontent.com/assets/417657/9984003/2d5e4d80-5fdd-11e5-851b-45d7a68825ca.png)
![landing page medium](https://cloud.githubusercontent.com/assets/417657/9984006/38804bf0-5fdd-11e5-8d8a-efc4d435bc30.png)
![landing page small](https://cloud.githubusercontent.com/assets/417657/9984008/3aa4ef1c-5fdd-11e5-9ed2-73c7831dae55.png)
![results](https://cloud.githubusercontent.com/assets/417657/9984010/3dcc8100-5fdd-11e5-92fa-7639e18d7304.png)
![results medium](https://cloud.githubusercontent.com/assets/417657/9984012/40c7c04a-5fdd-11e5-9f2b-c6d28071013f.png)
![results small](https://cloud.githubusercontent.com/assets/417657/9984013/4353d984-5fdd-11e5-871d-a21543eb541c.png)

**Comment by cweber** [comment]
The card heights are probably optimistic for the small screen view, but I'll have a better sense of how much room there is once I get a few cards wireframed.

**Comment by JennTopper** [comment]
The branding bar IS supposed to be on here, and Olivia was going to tweak
it to eliminate the big section that pulls down when you click "about" and
86 the Google+.

On Sun, Sep 20, 2015 at 9:51 PM, Caitlin <notifications@github.com> wrote:

> The card heights are probably optimistic for the small screen view, but
> I'll have a better sense of how much room there is once I get a few cards
> wireframed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/openfederal/issues/9#issuecomment-141854811>
> .
>



-- 

Jenn Topper
Communications Director | Sunlight Foundation
<http://www.sunlightfoundation.com/>
(o) 202-742-1520 ext. 226 | (c) 850-766-1267 | @jenntopper
<http://twitter.com/jenntopper>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by heyitsolivia** [comment]
I had @jalbertbowden make those tweaks to the branding bar—I think the changes just need to be deployed now but I may be the only one who has the keys. I'll check in with him about those.

See branding-bar issues [#21](https://github.com/sunlightlabs/branding-bar/issues/21), [#22](https://github.com/sunlightlabs/branding-bar/issues/22) and [#23](https://github.com/sunlightlabs/branding-bar/issues/23).

cc @cweber @JennTopper

**Comment by jalbertbowden** [comment]
tweaks done and committed. #21 is still open but only bc i'm not sure if we have the svgs or i need to create/ascertain them.
g+ is removed per that issue though.
